name: Go linters

on:
  - push
  - pull_request

jobs:
  golint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.22"
          - "1.23"
    name: Linters for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build project
        run: go build
      - name: Style linters
        run: make style
